Cheque.Web/Controllers/ChequeController.cs
using Cheque.Core.Contracts;
using Cheque.Web.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Cheque.Web.Controllers
{
    public class ChequeController : Controller
    {
        private IConverter _converter;
        public ChequeController(IConverter converter)
        {
            _converter = converter;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DisplayResult(ChequeModel cheque)
        {
            if (ModelState.IsValid)
            {
                cheque.AmountInWords = _converter.Convert(cheque.Amount);
                cheque.Date = cheque.Date.Date;
                return View("Index", cheque);
            }
            return View("Index");
        }
    }
}

Cheque.Web/Views/Cheque/Index.cshtml
@model Cheque.Web.Model.ChequeModel
@{
    ViewBag.Title = "Home Page";
}
<style>
    .jumbotron {
        font-size: 11pt;
    }

    .amountInWords {
        position: absolute;
        margin-top: 125px;
        margin-left: 20px;
        font-weight: bold;
    }

    .amount {
        position: absolute;
        margin-top: 110px;
        margin-left: 470px;
        font-weight: bold;
        font-size: 15pt;
    }

    .date {
        position: absolute;
        margin-top: 55px;
        margin-left: 480px;
        font-weight: bold;
    }

    .payee {
        position: absolute;
        margin-top: 95px;
        margin-left: 50px;
        font-weight: bold;
    }
</style>
@using (Html.BeginForm("DisplayResult", "Cheque"))
{
    <table>
        <tr>
            <td>Payee Name:</td>
            <td>
                @Html.TextBoxFor(x => x.Payee)<br />
                @Html.ValidationMessageFor(x => x.Payee)
            </td>
        </tr>
        <tr>
            <td>Amount:</td>
            <td>
                @Html.TextBoxFor(x => x.Amount)<br />
                @Html.ValidationMessageFor(x => x.Amount)
            </td>
        </tr>
        <tr>
            <td>Date:</td>
            <td>
                @Html.TextBoxFor(x => x.Date)<br />
                @Html.ValidationMessageFor(x => x.Date)
            </td>
        </tr>
        <tr><td></td><td><input type="submit" name="Submit" value="Submit" /></td></tr>

    </table>
}
@{
    if (Model != null)
    {
        <div class="jumbotron">

            <div class="amountInWords">@Model.AmountInWords</div>
            <div class="amount">@Model.Amount/-</div>
            <div class="date">@Model.Date.ToShortDateString()</div>
            <div class="payee">@Model.Payee</div>
            <img src="~/Content/img/cheque.png" />
        </div>
    }
}

Cheque.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cheque Automation", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Cheque")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br /><br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>